// GENERATED by scraper/build_ability_batch3.py — do not edit by hand; re-run the script.
// Ability batch 3 (Milestone 11): every card whose whole printed text fits the existing effects and
// triggers plus the batch-3 condition whitelist (epic #69). Skipped cards: data/abilities_skipped.json.

import { defineCard } from "./format";

export const IMPLEMENTED_BATCH3: Record<string, { name: string }> = {
  "s1-010": { name: "Hoplon" },
  "s1-038": { name: "Uma" },
  "s1-062": { name: "Leiter" },
  "s1-095": { name: "Shield of Hephaestus" },
  "s1-099": { name: "Ocrea" },
  "s3-001": { name: "Charlemagne" },
  "s3-058": { name: "Čhehúpahu Čhaŋksá" },
  "s4-058": { name: "Kamea-e Helal-e Irani" },
  "s5-016": { name: "Moctezuma II" },
  "s5-077": { name: "Mercurino Gattinara" },
  "s7-048": { name: "Klironomimena Opla" },
};

// Hoplon (special) — I tan I epi tas: "Your defense rolls gain +1 while you have a face-up weapon card."
defineCard("s1-010", { data: {"name": "I tan I epi tas", "trigger": "continuous", "effects": [{"kind": "defenseRoll", "amount": 1, "when": {"kind": "hasInPlay", "cardType": "weapon"}}]} });

// Uma (special) — Subayai: "Once per round, move two spaces."
defineCard("s1-038", { data: {"name": "Subayai", "trigger": "action", "effects": [{"kind": "move", "spaces": 2}], "usageLimit": "oncePerRound"} });

// Leiter (armor) — Naturlig: "Your defense rolls gain +1 if you are a water warrior."
defineCard("s1-062", { data: {"name": "Naturlig", "trigger": "continuous", "effects": [{"kind": "defenseRoll", "amount": 1, "when": {"kind": "elementIs", "element": "Water"}}]} });

// Shield of Hephaestus (special) — Dia Tis Pistis Aminomenos: "Your defense rolls gain +1 while you have a face-up inspiration card."
defineCard("s1-095", { data: {"name": "Dia Tis Pistis Aminomenos", "trigger": "continuous", "effects": [{"kind": "defenseRoll", "amount": 1, "when": {"kind": "hasInPlay", "cardType": "inspiration"}}]} });

// Ocrea (armor) — Armatura: "Your defense rolls gain +1 if you are a metal warrior."
defineCard("s1-099", { data: {"name": "Armatura", "trigger": "continuous", "effects": [{"kind": "defenseRoll", "amount": 1, "when": {"kind": "elementIs", "element": "Metal"}}]} });

// Charlemagne (warrior) — Férocité inlassable: "While you have at least three face-up support cards, your attack rolls gain +2."
defineCard("s3-001", { data: {"name": "Férocité inlassable", "trigger": "continuous", "effects": [{"kind": "attackRoll", "amount": 2, "when": {"kind": "faceUpSupportAtLeast", "n": 3}}]} });

// Čhehúpahu Čhaŋksá (weapon) — Wéeyala s'e Yaĥtáke: "Your basic attack rolls gain +2."
defineCard("s3-058", { data: {"name": "Wéeyala s'e Yaĥtáke", "trigger": "continuous", "effects": [{"kind": "attackRoll", "amount": 2, "when": {"kind": "attackKind", "is": "basic"}}]} });

// Kamea-e Helal-e Irani (weapon) — Ba Zoor: "Your basic attack rolls gain +1."
defineCard("s4-058", { data: {"name": "Ba Zoor", "trigger": "continuous", "effects": [{"kind": "attackRoll", "amount": 1, "when": {"kind": "attackKind", "is": "basic"}}]} });

// Moctezuma II (warrior) — Tezcatiliztli: "At the start of each round, if you did not win initiative, gain +1 speed for that round."
defineCard("s5-016", { data: {"name": "Tezcatiliztli", "trigger": "roundStart", "effects": [{"kind": "speed", "amount": 1}], "condition": {"kind": "lostInitiative"}, "duration": "thisRound"} });

// Mercurino Gattinara (inspiration) — Incitar Asalto – Reveal: "Your defense rolls this round get –1. Your attack rolls this round gain +3."
defineCard("s5-077", { data: {"name": "Incitar Asalto – Reveal", "trigger": "reveal", "effects": [{"kind": "defenseRoll", "amount": -1}, {"kind": "attackRoll", "amount": 3}], "duration": "thisRound"} });

// Klironomimena Opla (weapon) — Teleti tis Analipsis: "Your defense rolls gain +1."
defineCard("s7-048", { data: {"name": "Teleti tis Analipsis", "trigger": "continuous", "effects": [{"kind": "defenseRoll", "amount": 1}]} });
